name: fl_animaciones
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  animate_do: ^4.2.0
  audio_waveforms: ^1.3.0
  audioplayers: ^6.5.0
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_map: ^8.1.1
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.8.0
  geolocator: ^14.0.1
  go_router: ^15.2.0
  google_fonts: ^6.2.1
  image: 4.5.4
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  local_auth: ^2.3.0
  material_color_utilities: ^0.11.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0
  sensors_plus: ^6.1.1
  shared_preferences: ^2.5.3
dev_dependencies:
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.1
  package_rename: ^1.10.0
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/svg/
    - assets/shoes/
    - assets/music/
