name: fl_animaciones
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animate_do: ^3.3.4
  audioplayers: ^6.1.0
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_map: ^7.0.2
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  geolocator: ^13.0.2
  go_router: ^14.2.8
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  local_auth: ^2.3.0
  palette_generator: ^0.3.3+5
  permission_handler: ^11.3.1
  sensors_plus: ^6.1.0
  shared_preferences: ^2.3.2

  image: any
dev_dependencies:
  custom_lint: ^0.6.7
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0
  package_rename: ^1.7.1
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/svg/
    - assets/shoes/
    - assets/music/
